name: CI

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: |
       git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*

    - name: set up python
      uses: actions/setup-python@v1

    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx

    - name: Run sphinx-build
      run: |
        sphinx-build --version
        cd Documentation
        sphinx-build -b html . _build/html -E -a

        git worktree add gh-pages gh-pages
        rsync -avz --delete --exclude '.doctrees' _build/html gh-pages
        cd gh-pages
        git add -A
        echo "cache"
        git diff --cached
        echo "find"
        find .
