name: CI

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: |
       git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*

    - name: set up python
      uses: actions/setup-python@v1

    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx

    - name: Run sphinx-build
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        sphinx-build --version
        cd Documentation

        echo "buiilding new content..."
        sphinx-build -b html . _build/html -E -a

        echo "adding new content..."
        git worktree add gh-pages gh-pages
        
        find gh-pages/
        
        rsync -av --delete --exclude '.git' --exclude '.doctrees' _build/html/ gh-pages/
        cd gh-pages
        git add -A
        git config --local user.email "noreply@jdknight.me"
        git config --local user.name "GitHub Action"
        git commit -a -m "update"

        echo "adjusting url..."
        git remote set-url --push origin https://jdknight:$GITHUB_TOKEN@github.com/jdknight/test-github-doc
        
        find .
        
        echo "pushing new content..."
        git push origin gh-pages

        echo "done"
        
